/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CanceledRouteImport } from './routes/canceled'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CourseRouteImport } from './routes/course'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsVx9kRouteImport } from './routes/ops-vx9k'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as ApiCreateCheckoutSessionRouteImport } from './routes/api/create-checkout-session'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CanceledRoute = CanceledRouteImport.update({
  id: '/canceled',
  path: '/canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsVx9kRoute = OpsVx9kRouteImport.update({
  id: '/ops-vx9k',
  path: '/ops-vx9k',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateCheckoutSessionRoute =
  ApiCreateCheckoutSessionRouteImport.update({
    id: '/api/create-checkout-session',
    path: '/api/create-checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/canceled': typeof CanceledRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/ops-vx9k': typeof OpsVx9kRoute
  '/prompt': typeof PromptRoute
  '/success': typeof SuccessRoute
  '/toolkit': typeof ToolkitRoute
  '/api/create-checkout-session': typeof ApiCreateCheckoutSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/canceled': typeof CanceledRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/ops-vx9k': typeof OpsVx9kRoute
  '/prompt': typeof PromptRoute
  '/success': typeof SuccessRoute
  '/toolkit': typeof ToolkitRoute
  '/api/create-checkout-session': typeof ApiCreateCheckoutSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/canceled': typeof CanceledRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/ops-vx9k': typeof OpsVx9kRoute
  '/prompt': typeof PromptRoute
  '/success': typeof SuccessRoute
  '/toolkit': typeof ToolkitRoute
  '/api/create-checkout-session': typeof ApiCreateCheckoutSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/canceled'
    | '/checkout'
    | '/contact'
    | '/course'
    | '/faq'
    | '/legal'
    | '/login'
    | '/ops-vx9k'
    | '/prompt'
    | '/success'
    | '/toolkit'
    | '/api/create-checkout-session'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/canceled'
    | '/checkout'
    | '/contact'
    | '/course'
    | '/faq'
    | '/legal'
    | '/login'
    | '/ops-vx9k'
    | '/prompt'
    | '/success'
    | '/toolkit'
    | '/api/create-checkout-session'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/canceled'
    | '/checkout'
    | '/contact'
    | '/course'
    | '/faq'
    | '/legal'
    | '/login'
    | '/ops-vx9k'
    | '/prompt'
    | '/success'
    | '/toolkit'
    | '/api/create-checkout-session'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CanceledRoute: typeof CanceledRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CourseRoute: typeof CourseRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  OpsVx9kRoute: typeof OpsVx9kRoute
  PromptRoute: typeof PromptRoute
  SuccessRoute: typeof SuccessRoute
  ToolkitRoute: typeof ToolkitRoute
  ApiCreateCheckoutSessionRoute: typeof ApiCreateCheckoutSessionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canceled': {
      id: '/canceled'
      path: '/canceled'
      fullPath: '/canceled'
      preLoaderRoute: typeof CanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-vx9k': {
      id: '/ops-vx9k'
      path: '/ops-vx9k'
      fullPath: '/ops-vx9k'
      preLoaderRoute: typeof OpsVx9kRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-checkout-session': {
      id: '/api/create-checkout-session'
      path: '/api/create-checkout-session'
      fullPath: '/api/create-checkout-session'
      preLoaderRoute: typeof ApiCreateCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CanceledRoute: CanceledRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CourseRoute: CourseRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  OpsVx9kRoute: OpsVx9kRoute,
  PromptRoute: PromptRoute,
  SuccessRoute: SuccessRoute,
  ToolkitRoute: ToolkitRoute,
  ApiCreateCheckoutSessionRoute: ApiCreateCheckoutSessionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
